USE CP_BASE
GO
ALTER TABLE [dbo].[INVOICES]
	ADD CONSTRAINT W_L_INV
		FOREIGN KEY (WAREHOUSE_NUMBER) REFERENCES WAREHOUSE_LIST
			ON DELETE CASCADE ON UPDATE CASCADE; 

GO
ALTER TABLE [dbo].[STOR_PROD]
	ADD CONSTRAINT W_L_STOR_PROD
		FOREIGN KEY (WAREHOUSE_NUMBER) REFERENCES WAREHOUSE_LIST
			ON DELETE CASCADE ON UPDATE CASCADE; 

GO
ALTER TABLE [dbo].[INVOICES]
	ADD CONSTRAINT PROD_LIST_INV
		FOREIGN KEY (PROD_CODE) REFERENCES PROD_LIST
			ON DELETE CASCADE ON UPDATE CASCADE; 

GO
ALTER TABLE [dbo].[STOR_PROD]
	ADD CONSTRAINT PROD_LIST_STOR_PROD
		FOREIGN KEY (PROD_CODE) REFERENCES PROD_LIST
			ON DELETE CASCADE ON UPDATE CASCADE; 

