USE CP_BASE
GO
CREATE TYPE KEY_TYPE FROM INT NOT NULL;

--Изменения в таблице WAREHOUSE_LIST
GO
ALTER TABLE dbo.WAREHOUSE_LIST ALTER COLUMN WAREHOUSE_NUMBER KEY_TYPE;
GO
ALTER TABLE dbo.WAREHOUSE_LIST DROP CONSTRAINT DF__WAREHOUSE__WAREH__5CA1C101;
GO
ALTER TABLE dbo.WAREHOUSE_LIST ADD CONSTRAINT DF_WAREHOUSE_LIST_WAREHOUSE_NAME DEFAULT('') FOR WAREHOUSE_NAME;

--Изменения в таблице STOR_PROD
GO
ALTER TABLE [dbo].[STOR_PROD] ALTER COLUMN WAREHOUSE_NUMBER KEY_TYPE;
GO
ALTER TABLE [dbo].[STOR_PROD] ALTER COLUMN PROD_CODE KEY_TYPE;
GO
ALTER TABLE [dbo].[STOR_PROD] DROP CONSTRAINT CK__STOR_PROD__WAREH__625A9A57;
GO
ALTER TABLE [dbo].[STOR_PROD] ADD CONSTRAINT CH_STOR_PROD_WAREHOUSE_NOMBER CHECK(WAREHOUSE_NUMBER>=2000);
GO
ALTER TABLE [dbo].[STOR_PROD] DROP CONSTRAINT [CK__STOR_PROD__PROD___634EBE90]
GO
ALTER TABLE [dbo].[STOR_PROD]  WITH CHECK ADD CONSTRAINT CH_STOR_PROD_PROD_CODE CHECK (([PROD_CODE]>=(1)))
GO
ALTER TABLE [dbo].[STOR_PROD] DROP CONSTRAINT [DF__STOR_PROD__ALL_A__6442E2C9]
GO
ALTER TABLE [dbo].[STOR_PROD] ADD CONSTRAINT DF_STOR_PROD_ALL_AMOUNT DEFAULT ((0)) FOR [ALL_AMOUNT]
GO
ALTER TABLE [dbo].[STOR_PROD] DROP CONSTRAINT [DF__STOR_PROD__STOR___662B2B3B]
GO
ALTER TABLE [dbo].[STOR_PROD] ADD CONSTRAINT DF_STOR_PROD_STOR_COND DEFAULT ('') FOR [STOR_COND]
GO

--Изменения в таблице PROD_LIST
GO
ALTER TABLE PROD_LIST ALTER COLUMN PROD_CODE KEY_TYPE;
GO
ALTER TABLE PROD_LIST ADD CONSTRAINT DF_PROD_LIST_UNIT DEFAULT('') FOR UNIT;
GO
ALTER TABLE PROD_LIST ADD CONSTRAINT DF_PROD_LIST_PHONE_NUMBER DEFAULT('') FOR PHONE_NUMBER;
GO 
ALTER TABLE PROD_LIST ADD CONSTRAINT CH_PROD_LIST_PROD_CODE CHECK(PROD_CODE>=1);
GO

--Изменения в таблице INVOICES
GO
ALTER TABLE INVOICES ALTER COLUMN INVOICE_NUMBER KEY_TYPE;
GO
ALTER TABLE INVOICES ALTER COLUMN WAREHOUSE_NUMBER KEY_TYPE;
GO
ALTER TABLE INVOICES ALTER COLUMN PROD_CODE KEY_TYPE;
GO
ALTER TABLE INVOICES DROP CONSTRAINT CH_AMOUNT;
GO
ALTER TABLE INVOICES ADD CONSTRAINT CH_INVOICES_AMOUNT CHECK(AMOUNT>=0);
GO
ALTER TABLE INVOICES DROP CONSTRAINT CK__INVOICES__WAREHO__59C55456;
GO
ALTER TABLE INVOICES ADD CONSTRAINT CH_INVOICES_WAREHOUSE_NUMBER CHECK(WAREHOUSE_NUMBER>=2000);
GO
ALTER TABLE INVOICES DROP CONSTRAINT CK__INVOICES__WAREHO__59C55456;
GO
ALTER TABLE INVOICES ADD CONSTRAINT CH_INVOICES_WAREHOUSE_NUMBER CHECK(WAREHOUSE_NUMBER>=2000);  
GO
ALTER TABLE INVOICES DROP CONSTRAINT CK__INVOICES__PROD_C__58D1301D;
GO
ALTER TABLE INVOICES ADD CONSTRAINT CH_INVOICES_PROD_CODE CHECK([PROD_CODE]>=(1));
GO
ALTER TABLE INVOICES DROP CONSTRAINT CK__INVOICES__ATTRIB__57DD0BE4;
GO
ALTER TABLE INVOICES ADD CONSTRAINT CH_INVOICES_ATTRIBUTE CHECK([ATTRIBUTE]>=(0) AND [ATTRIBUTE]<=(1));
GO
ALTER TABLE INVOICES DROP CONSTRAINT DF__INVOICES__AMOUNT__55F4C372;
GO
ALTER TABLE INVOICES ADD CONSTRAINT DF_INVOICES_AMOUNT DEFAULT(0) FOR AMOUNT;
