USE CP_BASE
GO
CREATE TABLE [dbo].[INVOICES](
	[INVOICE_NUMBER] [int] IDENTITY(1000,1) NOT NULL, --CONSTRAINT PK_INV PRIMARY KEY CLUSTERED,
	[WAREHOUSE_NUMBER] [int] NOT NULL CHECK([WAREHOUSE_NUMBER]>=(2000)),
	[PERSON_IN_CHARGE] [nvarchar](100) NOT NULL,
	[PROD_CODE] [int] NOT NULL CHECK([PROD_CODE]>=(1)),
	[ATTRIBUTE] [bit] NOT NULL CHECK([ATTRIBUTE]>=(0) AND [ATTRIBUTE]<=(1)),
	[AMOUNT] [real] NULL DEFAULT (0) CONSTRAINT CH_AMOUNT CHECK ([AMOUNT]>=(0)),
	[MOD_DATE] [date] NULL,
	CONSTRAINT [PK_INVOICES] PRIMARY KEY CLUSTERED  (  [INVOICE_NUMBER] ASC ) ON [PRIMARY] 
	) ON [PRIMARY]
GO