USE CP_BASE
GO
CREATE TABLE [dbo].[WAREHOUSE_LIST] (
	[WAREHOUSE_NUMBER] [int] IDENTITY(2000,1) NOT NULL CONSTRAINT PK_WHS PRIMARY KEY CLUSTERED,
	[WAREHOUSE_NAME] [nvarchar](100) NOT NULL DEFAULT (''),
	[PERSON_IN_CHARGE] [nvarchar](100) NOT NULL
) ON [PRIMARY]
GO