USE [master]
GO
CREATE DATABASE [CP_BASE] ON PRIMARY
(NAME=N'CP_BASE', FILENAME=N'D:\db\CP_DB\CP_BASE.mdf',
SIZE = 3072KB, MAXSIZE=UNLIMITED, FILEGROWTH=1024KB)
LOG ON
(NAME=N'CP_BASE_log', FILENAME = N'D:\db\CP_DB\CP_BASE_log.ldf',
 SIZE=1024KB, MAXSIZE=2048, FILEGROWTH=10%)
 GO