USE [CP_BASE]
GO

--INSERT INTO dbo.INVOICES ([WAREHOUSE_NUMBER]
--           ,[PERSON_IN_CHARGE]
--           ,[PROD_CODE]
--           ,[ATTRIBUTE]
--           ,[AMOUNT]
--           ,[MOD_DATE])
--     VALUES
--           (2007
--           ,N'PIDOR'
--           ,7
--           ,1
--           ,3000
--           ,CAST(N'2017-09-18' AS Date)),
--		   (2007
--           ,N'PIDOR'
--           ,7
--           ,0
--           ,30
--           ,CAST(N'2017-09-18' AS Date)),
--		   (2004
--           ,N'PIDOR'
--           ,4
--           ,1
--           ,3000
--           ,CAST(N'2017-09-18' AS Date));


GO 
CREATE VIEW tmp_VIEW1(amount1,WAREHOUSE_NUMBER,  PROD_CODE) AS
SELECT SUM(i.AMOUNT) AS amount1, i.WAREHOUSE_NUMBER, i.PROD_CODE --INTO tmp_tbl1 
FROM INVOICES i WHERE i.ATTRIBUTE=1
GROUP BY i.PROD_CODE, i.WAREHOUSE_NUMBER;
GO
SELECT * FROM 	tmp_VIEW1;	
--DROP VIEW tmp_VIEW1;

GO 
CREATE VIEW tmp_VIEW0(amount0,WAREHOUSE_NUMBER,  PROD_CODE) AS
SELECT SUM(i.AMOUNT)*(-1) AS amount0, i.WAREHOUSE_NUMBER, i.PROD_CODE --INTO tmp_tbl1 
FROM INVOICES i WHERE i.ATTRIBUTE=0
GROUP BY i.PROD_CODE, i.WAREHOUSE_NUMBER;
GO
SELECT * FROM 	tmp_VIEW0;	


--DROP VIEW tmp_VIEW0;
--DROP VIEW tmp_VIEW1;


GO
CREATE VIEW VIEW_INC(WAREHOUSE_NUMBER, PROD_CODE, ATTRIBUTE, AMOUNT, S_W_N,S_P_C, ALL_AMOUNT) AS
SELECT i.WAREHOUSE_NUMBER, i.PROD_CODE, i.ATTRIBUTE, i.AMOUNT, s.WAREHOUSE_NUMBER, s.PROD_CODE, s.ALL_AMOUNT
FROM STOR_PROD s INNER JOIN INVOICES i ON
 s.WAREHOUSE_NUMBER<>i.WAREHOUSE_NUMBER AND s.PROD_CODE<>i.PROD_CODE
--GROUP BY  s.WAREHOUSE_NUMBER,s.PROD_CODE;
GO
SELECT * FROM VIEW_INC;
GO
DROP VIEW VIEW_INC;


SELECT  tmp_VIEW0.WAREHOUSE_NUMBER, tmp_VIEW0.PROD_CODE, amount0 
		FROM STOR_PROD s, tmp_VIEW0 WHERE
		(s.WAREHOUSE_NUMBER<>tmp_VIEW0.WAREHOUSE_NUMBER OR s.PROD_CODE<>tmp_VIEW0.PROD_CODE)
		GROUP BY tmp_VIEW0.WAREHOUSE_NUMBER, tmp_VIEW0.PROD_CODE, amount0;

SELECT  tmp_VIEW1.WAREHOUSE_NUMBER, tmp_VIEW1.PROD_CODE, amount1 
		FROM STOR_PROD s INNER JOIN tmp_VIEW1 ON
		(s.WAREHOUSE_NUMBER=tmp_VIEW1.WAREHOUSE_NUMBER OR s.PROD_CODE=tmp_VIEW1.PROD_CODE)
		WHERE 
		(s.WAREHOUSE_NUMBER<>tmp_VIEW1.WAREHOUSE_NUMBER AND s.PROD_CODE<>tmp_VIEW1.PROD_CODE)
		--s.WAREHOUSE_NUMBER<>tmp_VIEW1.WAREHOUSE_NUMBER AND s.PROD_CODE<>tmp_VIEW1.PROD_CODE 
		--(s.WAREHOUSE_NUMBER<>tmp_VIEW1.WAREHOUSE_NUMBER OR s.PROD_CODE=tmp_VIEW1.PROD_CODE) AND
		--(s.WAREHOUSE_NUMBER<>tmp_VIEW1.WAREHOUSE_NUMBER OR s.PROD_CODE<>tmp_VIEW1.PROD_CODE) AND
		--(s.WAREHOUSE_NUMBER=tmp_VIEW1.WAREHOUSE_NUMBER OR s.PROD_CODE<>tmp_VIEW1.PROD_CODE) 
		GROUP BY tmp_VIEW1.WAREHOUSE_NUMBER, tmp_VIEW1.PROD_CODE, amount1;
		
SELECT  tmp_VIEW1.WAREHOUSE_NUMBER, tmp_VIEW1.PROD_CODE, amount1 INTO #tmp_tbl_INV_1
FROM tmp_VIEW1
EXCEPT
SELECT s.WAREHOUSE_NUMBER, s.PROD_CODE, amount1 
FROM STOR_PROD s,tmp_VIEW1;
SELECT * FROM #tmp_tbl_INV_1;

SELECT  tmp_VIEW0.WAREHOUSE_NUMBER, tmp_VIEW0.PROD_CODE, amount0 INTO #tmp_tbl_INV_0
FROM tmp_VIEW0
EXCEPT
SELECT s.WAREHOUSE_NUMBER, s.PROD_CODE, amount0 
FROM STOR_PROD s,tmp_VIEW0;
SELECT * FROM #tmp_tbl_INV_0;

SELECT  #tmp_tbl_INV_1.WAREHOUSE_NUMBER, #tmp_tbl_INV_1.PROD_CODE,#tmp_tbl_INV_1.amount1+#tmp_tbl_INV_0.amount0 AS amountRes INTO #tmp_tbl_INV_Res 
FROM #tmp_tbl_INV_1 INNER JOIN #tmp_tbl_INV_0 ON 
(#tmp_tbl_INV_1.WAREHOUSE_NUMBER=#tmp_tbl_INV_0.WAREHOUSE_NUMBER) AND (#tmp_tbl_INV_1.PROD_CODE=#tmp_tbl_INV_0.PROD_CODE);
SELECT * FROM  #tmp_tbl_INV_Res;



SELECT #tmp_tbl_INV_1.WAREHOUSE_NUMBER, #tmp_tbl_INV_1.PROD_CODE, #tmp_tbl_INV_1.amount1 INTO #tmp_tbl_INV_ins_S_P
FROM #tmp_tbl_INV_1
EXCEPT
SELECT #tmp_tbl_INV_1.WAREHOUSE_NUMBER, #tmp_tbl_INV_1.PROD_CODE, #tmp_tbl_INV_1.amount1
FROM #tmp_tbl_INV_1 INNER JOIN  #tmp_tbl_INV_0 ON 
(#tmp_tbl_INV_1.WAREHOUSE_NUMBER=#tmp_tbl_INV_0.WAREHOUSE_NUMBER) AND (#tmp_tbl_INV_1.PROD_CODE=#tmp_tbl_INV_0.PROD_CODE);
 
SELECT * FROM #tmp_tbl_INV_ins_S_P;

SELECT * INTO #tmp_tbl_ins_S_P
FROM (SELECT * FROM #tmp_tbl_INV_ins_S_P
	  UNION 
	  SELECT * FROM #tmp_tbl_INV_Res) #tmp_tbl_ins_S_P;

SELECT * FROM #tmp_tbl_ins_S_P;



DECLARE @Count INT;
SET @Count=@@ROWCOUNT;
IF @Count >0
BEGIN
	INSERT INTO STOR_PROD(WAREHOUSE_NUMBER, PROD_CODE, LAST_MOD_DATE, ALL_AMOUNT)
			SELECT WAREHOUSE_NUMBER, PROD_CODE,GETDATE() ,amount1 
			FROM tmp_VIEW1
END
