CREATE TRIGGER BD_INVOICES ON dbo.INVOICES
   AFTER DELETE
AS 
BEGIN
	DECLARE @Count int;
	SET @Count=@@ROWCOUNT;
	IF @Count=0
		RETURN;
		SELECT SUM(d.AMOUNT) AS amount1, d.WAREHOUSE_NUMBER, d.PROD_CODE, d.ATTRIBUTE, d.MOD_DATE INTO #tmp_tbl1
		FROM deleted d WHERE d.ATTRIBUTE=1
		GROUP BY d.PROD_CODE, d.WAREHOUSE_NUMBER, d.ATTRIBUTE, d.MOD_DATE;
	SELECT SUM(d.AMOUNT) AS amount0, d.WAREHOUSE_NUMBER, d.PROD_CODE, d.ATTRIBUTE, d.MOD_DATE INTO #tmp_tbl0
		FROM inserted d WHERE d.ATTRIBUTE=0
		GROUP BY d.PROD_CODE, d.WAREHOUSE_NUMBER, d.ATTRIBUTE, d.MOD_DATE;
		--WHERE i.ATTRIBUTE=1
	UPDATE STOR_PROD
		SET ALL_AMOUNT = ALL_AMOUNT - amount1, LAST_MOD_DATE = tmp1.MOD_DATE
			FROM STOR_PROD s INNER JOIN #tmp_tbl1 tmp1 ON
				s.WAREHOUSE_NUMBER=tmp1.WAREHOUSE_NUMBER AND
				s.PROD_CODE=tmp1.PROD_CODE;
	
	UPDATE STOR_PROD
		SET ALL_AMOUNT = ALL_AMOUNT + amount0, LAST_MOD_DATE = tmp0.MOD_DATE
			FROM STOR_PROD s INNER JOIN #tmp_tbl0 tmp0 ON
				s.WAREHOUSE_NUMBER=tmp0.WAREHOUSE_NUMBER AND
				s.PROD_CODE=tmp0.PROD_CODE;

END
GO
