USE CP_BASE
GO
CREATE TRIGGER AI_INVOICES ON dbo.INVOICES
	FOR INSERT
AS 
BEGIN
	DECLARE @Count int;
	SET @Count=@@ROWCOUNT;
	IF @Count=0
		RETURN;
	--SET NOCOUNT ON;
	--	UPDATE STOR_PROD
	--	SET ALL_AMOUNT=ALL_AMOUNT+(SELECT SUM(AMOUNT) FROM inserted i 
	--		WHERE i.WAREHOUSE_NUMBER=STOR_PROD.WAREHOUSE_NUMBER AND
	--			i.PROD_CODE=STOR_PROD.PROD_CODE AND
	--				i.ATTRIBUTE=1);
	--	UPDATE STOR_PROD
	--	SET ALL_AMOUNT=ALL_AMOUNT-(SELECT SUM(AMOUNT) FROM inserted i 
	--		WHERE i.WAREHOUSE_NUMBER=STOR_PROD.WAREHOUSE_NUMBER AND
	--			i.PROD_CODE=STOR_PROD.PROD_CODE AND
	--				i.ATTRIBUTE=0);
	
	SELECT SUM(i.AMOUNT) AS amount1, i.WAREHOUSE_NUMBER, i.PROD_CODE, i.ATTRIBUTE, i.MOD_DATE INTO #tmp_tbl1
		FROM inserted i WHERE i.ATTRIBUTE=1
		GROUP BY i.PROD_CODE, i.WAREHOUSE_NUMBER, i.ATTRIBUTE, i.MOD_DATE ;
	SELECT SUM(i.AMOUNT) AS amount0, i.WAREHOUSE_NUMBER, i.PROD_CODE, i.ATTRIBUTE, i.MOD_DATE INTO #tmp_tbl0
		FROM inserted i WHERE i.ATTRIBUTE=0
		GROUP BY i.PROD_CODE, i.WAREHOUSE_NUMBER, i.ATTRIBUTE, i.MOD_DATE;
		--WHERE i.ATTRIBUTE=1
	UPDATE STOR_PROD
		SET ALL_AMOUNT = ALL_AMOUNT + amount1, LAST_MOD_DATE = tmp1.MOD_DATE
			FROM STOR_PROD s INNER JOIN #tmp_tbl1 tmp1 ON
				s.WAREHOUSE_NUMBER=tmp1.WAREHOUSE_NUMBER AND
				s.PROD_CODE=tmp1.PROD_CODE;
	
	UPDATE STOR_PROD
		SET ALL_AMOUNT = ALL_AMOUNT - amount0, LAST_MOD_DATE = tmp0.MOD_DATE
			FROM STOR_PROD s INNER JOIN #tmp_tbl0 tmp0 ON
				s.WAREHOUSE_NUMBER=tmp0.WAREHOUSE_NUMBER AND
				s.PROD_CODE=tmp0.PROD_CODE;
END
GO
