USE CP_BASE
GO
CREATE TRIGGER [dbo].[AU_INVOICES] ON [dbo].[INVOICES]
   AFTER UPDATE
AS 
BEGIN
	DECLARE @Count int;
	SET @Count=@@ROWCOUNT;
	IF @Count=0 RETURN;
	SET NOCOUNT ON;

   IF UPDATE(AMOUNT) OR UPDATE(PROD_CODE) OR UPDATE(WAREHOUSE_NUMBER) OR UPDATE(ATTRIBUTE)
		BEGIN
			SELECT * FROM deleted WHERE ATTRIBUTE=1
			SET @Count=@@ROWCOUNT;
			IF @Count>0 
				BEGIN
					UPDATE STOR_PROD
					SET ALL_AMOUNT= ALL_AMOUNT-(SELECT SUM(AMOUNT)
							FROM deleted d
							WHERE d.ATTRIBUTE=1 AND d.WAREHOUSE_NUMBER=STOR_PROD.WAREHOUSE_NUMBER AND d.PROD_CODE=STOR_PROD.PROD_CODE
							GROUP BY PROD_CODE,WAREHOUSE_NUMBER,ATTRIBUTE)
					WHERE PROD_CODE IN (SELECT PROD_CODE FROM deleted d1) AND WAREHOUSE_NUMBER IN (SELECT WAREHOUSE_NUMBER FROM deleted d1)
				END
			SELECT * FROM deleted WHERE ATTRIBUTE=0
			SET @Count=@@ROWCOUNT;
			IF @Count>0 
				BEGIN
					UPDATE STOR_PROD
					SET	ALL_AMOUNT= ALL_AMOUNT+(SELECT SUM(AMOUNT)
							FROM deleted d
							WHERE d.ATTRIBUTE=0 AND d.WAREHOUSE_NUMBER=STOR_PROD.WAREHOUSE_NUMBER AND d.PROD_CODE=STOR_PROD.PROD_CODE
							GROUP BY PROD_CODE,WAREHOUSE_NUMBER,ATTRIBUTE)
					WHERE PROD_CODE IN (SELECT PROD_CODE FROM deleted d1) AND WAREHOUSE_NUMBER IN (SELECT WAREHOUSE_NUMBER FROM deleted d1)
				END
			SELECT * FROM INSERTED WHERE ATTRIBUTE=1
			SET @Count=@@ROWCOUNT;
			IF @Count>0
				BEGIN
					UPDATE STOR_PROD
					SET ALL_AMOUNT=ALL_AMOUNT+(SELECT SUM(AMOUNT)
							FROM inserted i
							WHERE i.ATTRIBUTE=1 AND i.WAREHOUSE_NUMBER=STOR_PROD.WAREHOUSE_NUMBER AND i.PROD_CODE=STOR_PROD.PROD_CODE
							GROUP BY PROD_CODE, WAREHOUSE_NUMBER,ATTRIBUTE)
					WHERE PROD_CODE IN (SELECT PROD_CODE FROM inserted i1) AND WAREHOUSE_NUMBER IN (SELECT WAREHOUSE_NUMBER FROM inserted i1);
				END
			SELECT * FROM INSERTED WHERE ATTRIBUTE=0
			SET @Count=@@ROWCOUNT;
			IF @Count>0
				BEGIN
					UPDATE STOR_PROD
					SET	ALL_AMOUNT=ALL_AMOUNT-(SELECT SUM(AMOUNT)
							FROM inserted i
							WHERE i.ATTRIBUTE=0 AND i.WAREHOUSE_NUMBER=STOR_PROD.WAREHOUSE_NUMBER AND i.PROD_CODE=STOR_PROD.PROD_CODE
							GROUP BY PROD_CODE, WAREHOUSE_NUMBER,ATTRIBUTE)
					WHERE PROD_CODE IN (SELECT PROD_CODE FROM inserted i1) AND WAREHOUSE_NUMBER IN (SELECT WAREHOUSE_NUMBER FROM inserted i1);
				END
		END
    -- Insert statements for trigger here


END
GO
